### ISSUE TITLE
Missing dependency cryptography

### ISSUE THREAD

**Issue by diplix** [davecom/PyWeatherKit#2]
had to install cryptography to make it work, i.e. in a venv:

```
python3 -m venv pyweatherkit
source pyweatherkit/bin/activate
pip install wheel
pip install pyweatherkit
pip install cryptography
```

**Comment by davecom** [comment]
Thanks, it looks like the PyJWT dependency should be PyJWT[crypto] which will cause cryptography to be installed.

**Comment by davecom** [comment]
Close by version 0.0.2
