### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 8: invalid continuation byte

### ISSUE THREAD

**Issue by yodel-settles** [davecom/PyWeatherKit#4]
Are supposed to use the .p8 AuthKey_ or different format?

Found README sparse on key file path info

Trying to run:

python3 simple_test.py 

This is error:

"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 8: invalid continuation byte"

Can someone please help?

**Comment by davecom** [comment]
Yes, it's a .p8 key. You should checkout Apple's documentation about how to generate the key:

https://developer.apple.com/documentation/weatherkitrestapi/request_authentication_for_weatherkit_rest_api

Unfortunately, Apple makes it rather an involved process. Check that the command-line parameters that you passed to simple_test.py were correct. Can you provide more context about the error—what line is generating it. Please provide the full stack trace. Thanks.

**Comment by yodel-settles** [comment]
Hey, thanks for taking a look at this and for developing the project.

I just checked the command-line parameters and I think they are correct. I also took a look at the Apple doc you provided, I was actually hoping your code was going to do the heavy lifting for this p8 :)

Here is the full stack trace:

Traceback (most recent call last):
  File "PyWeatherKit/simple_test.py", line 36, in <module>
    client = WKClient(args.team_id, args.service_id, args.key_id, args.key_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PyWeatherKit/weatherkit/client.py", line 36, in __init__
    self.token = generate_token(
                 ^^^^^^^^^^^^^^^
  File "PyWeatherKit/weatherkit/token.py", line 37, in generate_token
    key = key_file.read()
          ^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 8: invalid continuation byte

**Comment by davecom** [comment]
I believe the error is saying that your keyfile is malformed. Sorry, I don't think this is something I can help you with but if you find out it's some kind of bug in the reading of the key file let me know.

**Comment by yodel-settles** [comment]
Using 'pip3 install PyJWT' instead of 'pip3 install jwt' fixed it for me. I uninstalled jwt and installed PyJWT. Thanks for making the module!
