### ISSUE TITLE
private id file

### ISSUE THREAD

**Issue by mikeyEcology** [davecom/PyWeatherKit#5]
Hi, Thank you for creating this package! What should the private id file look like? I tried setting my file up like this, because that's how I got the information, but I don't know what it should look like. 

```
text_for_private_id_file = f'''Name:{team_id}
Key ID:{key_id}
Services:{service_id}'''
```

For reference, I am at this step: `client = WKClient("YOUR TEAM ID", "YOUR SERVICE ID", "YOUR KEY ID", "PATH TO YOUR PRIVATE KEY FILE")` of the README

**Comment by davecom** [comment]
Hi Mikey,
I don't know where you got that formatting from, but the parameters here just the straight up strings of each of these values. So your team ID is something like a 10 digit alphanumeric code, your service id a is reverse domain, your key id is another 10 digit or so alphanumeric code, and your key file is the file path to your .p8 file.
Hope this helps,
David

**Comment by mikeyEcology** [comment]
Thank you David. Sorry to be so dense. I've never used the Apple development account and nobody at my company has either. I have my team_id and my key_id. 
Do you know where one finds a service_id? 
Also, what kind of information goes in the key file? Is this something I download?
I can't seem to find this information anywhere in Apple's developer docs and I keep clicking through links without finding any answers.

**Comment by mikeyEcology** [comment]
It looks like I need to be Admin on the account to generate this file. Wow-Apple Development is so much more complicated to use than anything else. There is so much unnecessary set up while other services just require a couple of numbers. Hopefully I'll get all of this sorted out eventually and then I'll get to use this package. Thanks for your help.
